# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "ahci"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "btrfs" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/4754ef4c-abe8-40f7-8346-8e017e9c109f";
    fsType = "btrfs";
    options = [
      "subvol=root"
      "compress=zstd"
      "noatime"
      "commit=120"
    ];
  };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/77d663dc-a8b2-4bac-a9bd-a2b173b698a7";
  boot.initrd.luks.devices."enc".preLVM = true;

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/4754ef4c-abe8-40f7-8346-8e017e9c109f";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd"
      "noatime"
      "commit=120"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/4754ef4c-abe8-40f7-8346-8e017e9c109f";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "compress=zstd"
      "noatime"
      "commit=120"
    ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/4754ef4c-abe8-40f7-8346-8e017e9c109f";
    fsType = "btrfs";
    options = [
      "subvol=persist"
      "compress=zstd"
      "noatime"
      "commit=120"
    ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/4754ef4c-abe8-40f7-8346-8e017e9c109f";
    fsType = "btrfs";
    options = [
      "subvol=log"
      "compress=zstd"
      "noatime"
      "commit=120"
    ];
    neededForBoot = true;
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/4754ef4c-abe8-40f7-8346-8e017e9c109f";
    fsType = "btrfs";
    options = [
      "subvol=snapshots"
      "compress=zstd"
      "noatime"
      "commit=120"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/AC72-0CDD";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s25.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
